---
# tasks file for update_rhel_packages
#- name: Update RHEL packages for security
#  command: /bin/dnf -y update --security
#  warn: false
#  register: dnf_update
#  until: dnf_update is not failed
#  retries: 5
- name: Update RHEL packages for security
  dnf:
    name: "*"
    state: latest
    disablerepo: "*"
    enablerepo: "rhel-8-for-x86_64-appstream-rpms,rhel-8-for-x86_64-baseos-rpms,satellite-tools-6.?-for-rhel-8-x86_64-rpms"
    exclude: ""
    security: yes
  become: yes
  register: dnf_update
  until: dnf_update is not failed
  retries: 5

- name: Show dnf results
  debug:
    msg: "{{ dnf_update }}"

- name: Update stage to updated
  set_fact:
    provisioning_stage: "updated"
    cacheable: yes
  when: dnf_update is not failed
