---
# tasks file for update_rhel_packages
- name: Check update for security
  command: /bin/dnf check-update --security
  args:
    warn: no
  become: yes
  register: check_update
  failed_when: check_update.rc == 1
  changed_when: False
  until: check_update is not failed
  retries: 5
  when: dnf_check | bool and dnf_security | bool