---
# tasks file for update_rhel_packages
- name: Update RHEL packages for security
  dnf:
    name: "*"
    state: latest
    update_only: yes
    security: no
    skip_broken: no
  register: dnf_update
  until: dnf_update is not failed
  retries: 5

- name: Show dnf results
  debug:
    msg: "{{ dnf_update }}"

- name: Update stage to updated
  set_fact:
    provisioning_stage: "updated"
    cacheable: yes
  when: dnf_update is not failed
