---
# tasks file for update_rhel_packages
- name: Check update for security
  command: /bin/dnf check-update
  args:
    warn: no
  become: yes
  register: check_update
  failed_when: check_update.rc == 1
  until: check_update is not failed
  retries: 5

- name: Show check results
  debug:
    msg: "{{ check_update }}"

- name: Update RHEL packages for security
  command: /bin/dnf -y update --security
  args:
    warn: no
  become: yes
  register: dnf_update
  until: dnf_update is not failed
  retries: 5

- name: Show dnf results
  debug:
    msg: "{{ dnf_update }}"

#- name: Update stage to updated
#  set_fact:
#    provisioning_stage: "updated"
#    cacheable: yes
#  when: dnf_update is not failed
